---

- name: Update homebrew
  command: "brew update"
  tags:
    - base
    - brew
    - brew-cask
    - update

- name: Install base homebrew packages
  homebrew:
    name: "{{ item.name }}"
    install_options: "{{ item.install_options | default('') }}"
    path: "{{ item.path| default('/usr/local/bin') }}"
    state: "{{ item.state | default('latest') }}"
    update_homebrew: "{{ item.update_homebrew | default('no') }}"
    upgrade_all: "{{ item.upgrade_all | default('no') }}"
  with_items: "{{ brew_base_packages }}"
  tags:
    - base
    - brew

- name: Install brew cask applications
  homebrew_cask:
    name: "{{ item.name }}"
    accept_external_apps: "{{ item.accept_external_apps | default('no') }}"
    greedy: "{{ item.greedy | default('no') }}"
    install_options: "{{ item.install_options | default('') }}"
    path: "{{ item.path| default('/usr/local/bin') }}"
    state: "{{ item.state | default('latest') }}"
    update_homebrew: "{{ item.update_homebrew | default('no') }}"
    upgrade_all: "{{ item.upgrade_all | default('no') }}"
  with_items: "{{ brew_cask_applications }}"
  tags:
    - base
    - brew
    - brew-cask

- name: Cleanup homebrew
  command: "brew cleanup -s"
  ignore_errors: True
  tags:
    - base
    - brew
    - cleanup

- name: Check is pinentry-mac installed
  shell: command -v pinentry-mac  >/dev/null 2>&1
  register: pinentry_mac_exist
  ignore_errors: yes

- name: Copy pinentry-mac conf
  command: 'echo "pinentry-program /usr/local/bin/pinentry-mac" >> ~/.gnupg/gpg-agent.conf'
  when: pinentry_mac_exist.rc == 0
  tags:
    - pinentry-mac-conf-copy
